[theme]
base            = "light"
primaryColor    = "#6B4226"
backgroundColor = "#F0F7FA"
secondaryBackgroundColor = "#F5EFE0"
textColor       = "#2D1F0F"
font            = "sans serif"

[server]
headless        = true
enableCORS      = false

[browser]
gatherUsageStats = false
